### ISSUE TITLE
博主你好，我有点问题

### ISSUE THREAD

**Issue by Grived** [stay-leave/weibo-public-opinion-analysis#15]
博主你好，我是初次接触人工智能就被要求制作类似项目的新手，安装完环境看完说明后还是不会跑，如果你有空能麻烦你出个详细一些的教学吗

**Comment by stay-leave** [comment]
流程:
1.爬取数据: 爬取正文，爬取评论，爬取用户信息
2.清洗数据: 清洗正文，清洗评论
3.情感分析: 针对评论进行，将其输入Baidu-aip的接口，获得情感分类结果。
4.主题分析: 针对正文进行，将其按月份聚合，进行分词成TXT，导入lda进行训练，找到最优模型进行结果输出。
2.主题演化趋势: 根据主题分析结果，将关键词之间进行链接，绘制主题河流图。
主要就是这些。

**Comment by Grived** [comment]
但我在清洗数据的时候，用你给的数据集却报了错：Traceback (most recent call last):   File "Z:\项目\微博\weibo-public-opinion-analysis-main\weibo-crawler\data cleaning.py", line 143, in <module>     filenames=os.listdir(r'评论_xlsx')#文件名 FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '评论_xlsx'，查了很多资料也没有找到，请问博主知道是为什么吗

**Comment by stay-leave** [comment]
那就用绝对路径定位文件夹

**Comment by Grived** [comment]
还是不行：Traceback (most recent call last):   File "Z:\项目\微博\weibo-public-opinion-analysis-main\weibo-crawler\data cleaning.py", line 143, in <module>     filenames=os.listdir('Z:\项目\微博\weibo-public-opinion-analysis-main\weibo-crawler\评论.xlsx')#文件名 NotADirectoryError: [WinError 267] 目录名称无效。: 'Z:\\项目\\微博\\weibo-public-opinion-analysis-main\\weibo-crawler\\评论.xlsx'

**Comment by stay-leave** [comment]
要的是文件夹，好好百度下

**Comment by Grived** [comment]
感谢！

**Comment by SAHSNGE** [comment]
> 博主你好，我是初次接触人工智能就被要求制作类似项目的新手，安装完环境看完说明后还是不会跑，如果你有空能麻烦你出个详细的一些教学吗？

同学你有做成功了嘛，方便交流一下嘛
