### ISSUE TITLE
作者，我在做数据清洗的时候遇到了这样的报错，这是缺少什么文件吗？

### ISSUE THREAD

**Issue by caasascascaw** [stay-leave/weibo-public-opinion-analysis#31]
Traceback (most recent call last):
  File "D:\微博\data cleaning.py", line 145, in <module>
    items = file(r'D:\微博\评论.xlsx' + j)
  File "D:\微博\data cleaning.py", line 117, in file
    data = xlrd.open_workbook(inpath, encoding_override='utf-8')
  File "D:\py\anaconda\lib\site-packages\xlrd\__init__.py", line 166, in open_workbook
    file_format = inspect_format(filename, file_contents)
  File "D:\py\anaconda\lib\site-packages\xlrd\__init__.py", line 60, in inspect_format
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\微博\\评论.xlsx.idea'

**Comment by stay-leave** [comment]
file是要传文件，路径要对
